apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.passwordSecret.name }}
type: Opaque
data:
  {{ .Values.database.passwordSecret.key }}: {{ .Values.database.passwordSecret.value | b64enc }}
