apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.rootPasswordSecret.name }}
type: Opaque
data:
  {{ .Values.database.rootPasswordSecret.key }}: {{ .Values.database.rootPasswordSecret.value | b64enc }}
