namespace: login-app
image:
  repository: mariadb
  tag: latest
  pullPolicy: IfNotPresent

persistence:
  enabled: true
  storageClass: "-"
  size: 1Gi
  existingClaim: mariadb-pvc

service:
  name: mariadb
  type: ClusterIP
  port: 3306

database:
  name: mysql
  user: user
  passwordSecret:
    name: mariadb-passwords
    key: password
    value: user
  rootPasswordSecret:
    name: mariadb-root-password
    key: MARIADB_ROOT_PASSWORD
    value: root

replicaCount: 1
secrets:
  root:
    name: mariadb-root-password
    password: root
